# Generated by Django 4.2.16 on 2024-10-28 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('hash_value', models.CharField(max_length=64, unique=True, verbose_name='Хеш данных')),
                ('data_json', models.JSONField(verbose_name='Данные')),
            ],
        ),
    ]
